name: Generate Index

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  generate-index:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # If you do not need npm dependencies, you can skip this step
      # - name: Install dependencies
      #   run: npm install

      - name: Run the generate-index.js script
        run: node generate-index.js
